version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /root/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"

  le-companion:
    volumes:
      - /root/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    image: jrcs/letsencrypt-nginx-proxy-companion


  wp:
    image: cloudgenius/myownwordpress
    environment:
      - VIRTUAL_HOST=proper.cloudgeni.us
      - LETSENCRYPT_HOST=proper.cloudgeni.us
      - LETSENCRYPT_EMAIL=nilesh@cloudgeni.us
      - WORDPRESS_DB_PASSWORD=example
    ports:
      - "80"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example

  redis:
    image: redis
    ports:
      - "6379"
